package com.eventgateway.api.entity;

import java.math.BigDecimal;
import java.time.Instant;

import com.eventgateway.api.dto.event.EventType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.domain.Persistable;

/**
 * Durable gateway ledger record keyed by upstream event id.
 *
 * <p>The upstream event id is assigned by the caller rather than generated by
 * the database. Spring Data's default "new entity" detection treats a non-null
 * id as an existing entity, which can route {@code save} through merge semantics.
 * For this ledger that is unsafe under concurrent duplicate delivery because
 * multiple threads could believe they created the same event and call Account
 * Service more than once. Implementing {@link Persistable} lets new records use
 * insert semantics so the database primary key remains the final idempotency
 * guard.</p>
 */
@Getter
@Setter
@Entity
@NoArgsConstructor
@Table(name = "event_records")
public class EventRecord implements Persistable<String> {

    @Id
    @Column(name = "event_id", nullable = false, length = 128)
    private String eventId;

    @Column(name = "account_id", nullable = false, length = 128)
    private String accountId;

    @Enumerated(EnumType.STRING)
    @Column(name = "event_type", nullable = false, length = 16)
    private EventType type;

    @Column(name = "amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal amount;

    @Column(name = "currency", nullable = false, length = 3)
    private String currency;

    @Column(name = "event_timestamp", nullable = false)
    private Instant eventTimestamp;

    @Lob
    @Column(name = "metadata_json")
    private String metadataJson;

    @Enumerated(EnumType.STRING)
    @Column(name = "apply_status", nullable = false, length = 32)
    private ApplyStatus applyStatus;

    @Column(name = "account_service_error", length = 1024)
    private String accountServiceError;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Transient
    private boolean newRecord = true;

    /**
     * Returns the identifier Spring Data uses for repository operations.
     *
     * <p>This delegates to {@code eventId} because the event id is both the
     * upstream idempotency key and the database primary key.</p>
     *
     * @return upstream event id
     */
    @Override
    public String getId() {
        return eventId;
    }

    /**
     * Tells Spring Data whether this entity should be inserted or merged.
     *
     * <p>New application-created records return {@code true} so repository
     * {@code saveAndFlush} performs an insert and primary-key conflicts are
     * surfaced. JPA-loaded records are marked as existing by lifecycle callbacks
     * and return {@code false}, allowing normal updates such as changing
     * {@link #applyStatus} from {@link ApplyStatus#PENDING} to
     * {@link ApplyStatus#APPLIED}.</p>
     *
     * @return true when the entity has not yet been persisted or loaded
     */
    @Override
    public boolean isNew() {
        return newRecord;
    }

    /**
     * Marks the entity as no longer new after JPA persists or loads it.
     *
     * <p>This lifecycle callback prevents a previously persisted row from being
     * inserted again when the service later saves status updates.</p>
     */
    @PostLoad
    @PostPersist
    void markNotNew() {
        this.newRecord = false;
    }
}
